version: '3.0'

services:
  zarg-bot:
    image: golang:alpine
    restart: unless-stopped
    volumes:
      - .:/app
      - go-cache:/root/.cache
    working_dir: /app
    command: go run ./cmd/bot/main.go
    env_file: .env

volumes:
  go-cache:
